version: 2

updates:
  # JS / React Native
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Android (Gradle)
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"

  # iOS (CocoaPods)
  - package-ecosystem: "bundler"
    directory: "/ios"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cocoapods"
    directory: "/ios"
    schedule:
      interval: "weekly"
